name = "svr-cf"
main = "src/index.js"
compatibility_date = "2024-09-19"
routes = [{ pattern = "street-view-runner.noue.org/*", zone_name = "noue.org" }]

 # The following configuration unconditionally invokes the Worker script at
 # `src/index.ts`, which can programatically fetch assets via the ASSETS binding
[assets]
directory = "./public/"
binding = "ASSETS"
run_worker_first = true

[dev]
port = 8787

# Note: Do not set secrets in code. For local dev, use `.dev.vars`.

[[kv_namespaces]]
binding = "SVR_KV"
# Placeholder IDs work for local dev; set real IDs after creating KV in Cloudflare
id = "a391c69e3e8d44c4840d9d4da02f5a6c"

[[d1_databases]]
binding = "SVR_DB"
database_name = "svr-db"
database_id = "297f593c-1925-4f03-ab2d-8d26efc8272d"
